FROM mongo:latest

# Copia o dataset e o script de importação para a pasta de inicialização
COPY mongo-init/repairs.json /docker-entrypoint-initdb.d/
COPY mongo-init/import.sh /docker-entrypoint-initdb.d/
